#!/bin/bash
iatest=$(expr index "$-" i)

# {{{ Interactive check

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# -------------------------------------------------------------------------- }}}
# {{{ Source global definitions
if [ -f /etc/bash.bashrc ]; then
	. /etc/bash.bashrc
fi

# Enable bash programmable completion features in interactive shells
if [ -f /usr/share/bash-completion/bash_completion ]; then
	. /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi

# -------------------------------------------------------------------------- }}}

# {{{ Ignore upper and lowercase when TAB completion

# bind "set completion-ignore-case on"
# Ignore case on auto-completion
# Note: bind used instead of sticking these in .inputrc
if [[ $iatest -gt 0 ]]; then bind "set completion-ignore-case on"; fi

# Show auto-completion list automatically, without double tab
if [[ $iatest -gt 0 ]]; then bind "set show-all-if-ambiguous On"; fi

# -------------------------------------------------------------------------- }}}

# Disable the bell
if [[ $iatest -gt 0 ]]; then bind "set bell-style visible"; fi

# {{{ Disable ctrl-s, ctrl-q, and set infinite history.

# stty -ixon
# Allow ctrl-S for history navigation (with ctrl-R)
[[ $- == *i* ]] && stty -ixon

HISTSIZE='' HISTFILESIZE=''

# -------------------------------------------------------------------------- }}}
# Check the window size after each command and, if necessary, update the values of LINES and COLUMNS
shopt -s checkwinsize

# Causes bash to append to history instead of overwriting it so if you start a new terminal, you have old session history
shopt -s histappend
PROMPT_COMMAND='history -a'

# Define directory exports that my_functions use.

CFGHOME=$HOME/.config
export CFGHOME

GITHOME=$HOME/REPOS
export GITHOME

GITPATH=$GITHOME
export GITPATH

DOT_INST=$GITHOME/re_inst
export DOT_INST

if [ -d $DOT_INST/bin ]; then
	BIN_INST=$DOT_INST/bin
	export BIN_INST
fi

DOT_SHELL=$GITHOME/re_shell
export DOT_SHELL

SHELLSOURCE=$DOT_SHELL/sources
export SHELLSOURCE

BIN_SHELL=$DOT_SHELL/bin
export BIN_SHELL

DOT_RUN=$GITHOME/re_run
export DOT_RUN

if [ -d $DOT_RUN/bin ]; then
	BIN_RUN=$DOT_RUN/bin
	export BIN_RUN
fi

# SSHHOME=$GITHOME/ssh
# export SSHHOME
#
# WIKIHOME=$GITHOME/wiki
# export WIKIHOME

# {{{ Customize my shell. Array order matters.

my_array=("functions" "exports" "aliases" "paths" "completions" "prompt")

for m in "${my_array[@]}"; do
	[[ -f "$SHELLSOURCE/my_$m" ]] && source "$SHELLSOURCE/my_$m"
done

# Load my keys.
# sshkeys

# -------------------------------------------------------------------------- }}}
echo ${HOSTNAME} "on" ${OSTYPE}

# Source the Lazyman shell initialization for aliases and nvims selector
# shellcheck source=.config/nvim-Lazyman/.lazymanrc
#[ -f ~/.config/nvim-Lazyman/.lazymanrc ] && source ~/.config/nvim-Lazyman/.lazymanrc
# Source the Lazyman .nvimsbind for nvims key binding
# shellcheck source=.config/nvim-Lazyman/.nvimsbind
#[ -f ~/.config/nvim-Lazyman/.nvimsbind ] && source ~/.config/nvim-Lazyman/.nvimsbind

if command -v zoxide >/dev/null; then
	eval "$(zoxide init bash)"
fi

#######################################################
# Set the ultimate amazing command prompt
#######################################################

# Install Starship - curl -sS https://starship.rs/install.sh | sh

# eval "$(starship init bash)"

#Autojump

if [ -f "/usr/share/autojump/autojump.sh" ]; then
	. /usr/share/autojump/autojump.sh
elif [ -f "/usr/share/autojump/autojump.bash" ]; then
	. /usr/share/autojump/autojump.bash
else
	echo "can't found the autojump script"
fi

alias hug="hugo server -F --bind=10.0.0.210 --baseURL=http://10.0.0.210"
