## PATH for Awesomewm 
#export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

# export PATH="$HOME/.local/share/bob/nvim-bin:$PATH"

#export PATH="/home/linuxbrew/.linuxbrew/bin"

# awesome-client "local naughty=require('naughty'); require('awful').spawn.easy_async('env', function(out) naughty.notify({title="ENV", text=out})end)"

# export XDG_CURRENT_DESKTOP="KDE"
# export XDG_CONFIG_HOME=$HOME/.config
# export XDG_CURRENT_DESKTOP="KDE"

if [ -d "$HOME/keysdir" ]; then 
  export KEYSDIR="$HOME/keysdir"
  source $KEYSDIR/export
else
  echo "api-key dir not found"
fi
