#!/bin/bash

# {{{ Linux only machines.

# NOTE: When order matters:  PrependToPath (beginn) and appendToPath (end).

# Programming languages.
# prependToPath "$HOME"/.cargo/bin

# Ruby Environment Manager
if programExists rbenv; then
	eval "$(rbenv init - n)"
fi

# prependToPath only prepends to the path when the directory exists.
# prependToPath "$HOME"/bin
# prependToPath "$HOME"/.bin
# prependToPath "$HOME"/.local/bin
# prependToPath "$HOME"/.npm/bin
# prependToPath "$HOME"/.luarocks/bin

prependToPath "$HOME"/.local/share/nvim/mason/bin

appendToPath "$HOME"/.config/guix/current/bin
appendToPath "$HOME"/.guix-profile/bin

prependToPath "$HOME"/.local/share/bob/nvim-bin

appendToPath "/usr/local/go/bin"
appendToPath "/usr/games"

appendToPath "$BIN_INST"
# appendToPath "$BIN_SHELL"
# appendToPath "$BIN_RUN"

for d in $(command du "$BIN_SHELL" | cut -f2); do
	if [ -d "$d" ]; then
		appendToPath "$d"
	fi
done

for d in $(command du "$BIN_RUN" | cut -f2); do
	if [ -d "$d" ]; then
		appendToPath "$d"
	fi
done
# Homebrew
case "${OSTYPE}" in
linux*) brew_path="/home/linuxbrew/.linuxbrew" ;;
darwin*) brew_path="/opt/homebrew" ;;
esac
if [[ -f "${brew_path}/bin/brew" ]]; then
	eval "$("${brew_path}"/bin/brew shellenv)"
fi
# appendToPath "/home/linuxbrew/.linuxbrew/bin"
# appendToPath "/home/linuxbrew/.linuxbrew/sbin"

# Conda
case "${OSTYPE}" in
linux*) CONDA_PREFIX="/home/ru/miniconda3" ;;
darwin*) CONDA_PREFIX="/home/ru/miniconda3" ;;
esac
if [[ -f ${CONDA_PREFIX}/bin/conda ]]; then
	eval "$("${CONDA_PREFIX}/bin/conda" "shell.zsh" "hook")"
fi
# -------------------------------------------------------------------------- }}}
